
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Beau0303/springcloud/
          searchPaths: Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
